### ISSUE TITLE
go to analysis action on alignment tool

### ISSUE THREAD

**Issue by LuizMVB** [LuizMVB/olatcg-frontend#11]
When the user is in the last step of the sequence alignment tool, there should be a button that allows him to be redirected to the analysis he has just done in this procedure

You need to add this action to this button

![Image](https://user-images.githubusercontent.com/43626451/189813357-66cc986d-bf35-4507-8cab-2825b3cac0c7.png)

**Comment by leticiamaiat** [comment]
Fixed on [github.com/LuizMVB/olatcg-frontend/issues/13](url)
